### ISSUE TITLE
Better handling of backgrounding when using elapsed

### ISSUE THREAD

**Issue by CNick** [jarrodldavis/dotfiles#1]
When using elapsed, I often wish to place the job in the background by appending & at the end of my command like so:

```
./elapsed -d "wget the backup from origin server" -l wget.log -c "wget 'https://example.com/backup.zip'" &
```

When I do that, I still get output from the command, and it's difficult to use `disown` so I can leave the job running even after leaving the shell.

**Comment by jarrodldavis** [comment]
I've added a new option, `-s`, that will suppress output from the command from being printed to `stdout`. The output is still written to the log file, so  you can use `tail -f <logfile>` to view the output in realtime if needed.
